name = "TargetedLearning"                                                                                  
uuid = "9f0613f6-9d83-11ec-b909-0242ac120002"                                                                      
version = "0.1.0"    